server {
    listen 80;
    root /usr/share/nginx/html;
    index index.html;

    location ~* \.(html|js|css)$ {
        add_header Cache-Control "no-cache, must-revalidate";
        expires 0;
    }

    location / {
        try_files $uri $uri/ /index.html;
    }
}
